// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/gluetun/internal/updater/loop (interfaces: Logger,Updater)
//
// Generated by this command:
//
//	mockgen -destination=mocks_test.go -package=loop . Logger,Updater
//

// Package loop is a generated GoMock package.
package loop

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockLogger) Error(s string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", s)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), s)
}

// Info mocks base method.
func (m *MockLogger) Info(s string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Info", s)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), s)
}

// Warn mocks base method.
func (m *MockLogger) Warn(s string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warn", s)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerMockRecorder) Warn(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), s)
}

// MockUpdater is a mock of Updater interface.
type MockUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockUpdaterMockRecorder
	isgomock struct{}
}

// MockUpdaterMockRecorder is the mock recorder for MockUpdater.
type MockUpdaterMockRecorder struct {
	mock *MockUpdater
}

// NewMockUpdater creates a new mock instance.
func NewMockUpdater(ctrl *gomock.Controller) *MockUpdater {
	mock := &MockUpdater{ctrl: ctrl}
	mock.recorder = &MockUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdater) EXPECT() *MockUpdaterMockRecorder {
	return m.recorder
}

// UpdateServers mocks base method.
func (m *MockUpdater) UpdateServers(ctx context.Context, providers []string, minRatio float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServers", ctx, providers, minRatio)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateServers indicates an expected call of UpdateServers.
func (mr *MockUpdaterMockRecorder) UpdateServers(ctx, providers, minRatio any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServers", reflect.TypeOf((*MockUpdater)(nil).UpdateServers), ctx, providers, minRatio)
}
