// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces_local.go
//
// Generated by this command:
//
//	mockgen -destination=mocks_local_test.go -package=loop -source interfaces_local.go
//

// Package loop is a generated GoMock package.
package loop

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// Mocktimer is a mock of timer interface.
type Mocktimer struct {
	ctrl     *gomock.Controller
	recorder *MocktimerMockRecorder
	isgomock struct{}
}

// MocktimerMockRecorder is the mock recorder for Mocktimer.
type MocktimerMockRecorder struct {
	mock *Mocktimer
}

// NewMocktimer creates a new mock instance.
func NewMocktimer(ctrl *gomock.Controller) *Mocktimer {
	mock := &Mocktimer{ctrl: ctrl}
	mock.recorder = &MocktimerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocktimer) EXPECT() *MocktimerMockRecorder {
	return m.recorder
}

// C mocks base method.
func (m *Mocktimer) C() <-chan time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "C")
	ret0, _ := ret[0].(<-chan time.Time)
	return ret0
}

// C indicates an expected call of C.
func (mr *MocktimerMockRecorder) C() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "C", reflect.TypeOf((*Mocktimer)(nil).C))
}

// Reset mocks base method.
func (m *Mocktimer) Reset(d time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Reset", d)
}

// Reset indicates an expected call of Reset.
func (mr *MocktimerMockRecorder) Reset(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*Mocktimer)(nil).Reset), d)
}

// Stop mocks base method.
func (m *Mocktimer) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MocktimerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*Mocktimer)(nil).Stop))
}
