// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces_local.go
//
// Generated by this command:
//
//	mockgen -destination=mocks_local_test.go -package=loop -source interfaces_local.go
//

// Package loop is a generated GoMock package.
package loop

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// Mockticker is a mock of ticker interface.
type Mockticker struct {
	ctrl     *gomock.Controller
	recorder *MocktickerMockRecorder
	isgomock struct{}
}

// MocktickerMockRecorder is the mock recorder for Mockticker.
type MocktickerMockRecorder struct {
	mock *Mockticker
}

// NewMockticker creates a new mock instance.
func NewMockticker(ctrl *gomock.Controller) *Mockticker {
	mock := &Mockticker{ctrl: ctrl}
	mock.recorder = &MocktickerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockticker) EXPECT() *MocktickerMockRecorder {
	return m.recorder
}

// C mocks base method.
func (m *Mockticker) C() <-chan time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "C")
	ret0, _ := ret[0].(<-chan time.Time)
	return ret0
}

// C indicates an expected call of C.
func (mr *MocktickerMockRecorder) C() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "C", reflect.TypeOf((*Mockticker)(nil).C))
}

// Reset mocks base method.
func (m *Mockticker) Reset(d time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Reset", d)
}

// Reset indicates an expected call of Reset.
func (mr *MocktickerMockRecorder) Reset(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*Mockticker)(nil).Reset), d)
}

// Stop mocks base method.
func (m *Mockticker) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MocktickerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*Mockticker)(nil).Stop))
}
